version: '3'
services:
  postgres-db:
    image: "postgres:12"
    container_name: "node-test-db"
    environment:
      - POSTGRES_USER=node-test
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=node-test
    restart: always
    ports:
      - '5432:5432'
